# Generated by Django 5.1.4 on 2024-12-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_date", models.DateField(auto_now_add=True)),
                ("expected_return_date", models.DateField()),
                ("actual_return_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expected_return_date__gt", models.F("borrow_date"))
                        ),
                        name="expected_return_date_gt_borrow_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("actual_return_date__gt", models.F("borrow_date"))
                        ),
                        name="actual_return_date_gt_borrow_date",
                    ),
                ],
            },
        ),
    ]
